<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );

# If PHP's memory limit is very low, some operations may fail.
# ini_set( 'memory_limit', '20M' );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename         = "WVO Designs Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/wiki";
$wgScriptExtension  = ".php";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "webmaster@wvodesigns.com";
$wgPasswordSender = "webmaster@wvodesigns.com";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBname           = "wvodesig_wikidb";
$wgDBuser           = "wvodesig_wiki";
$wgDBpassword       = "/|cWBiAamB/Z";

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = true;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = true;
$wgUseImageMagick = false;
$wgImageMagickConvertCommand = "/usr/bin/convert";

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
# $wgShellLocale = "en_US.UTF-8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

$wgLocalInterwiki   = strtolower( $wgSitename );

$wgLanguageCode = "en";

$wgSecretKey = "b42a817d07e40e5264cdd359d0ea38d79d05afe68badfd093c38bbecc45466c0";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'monobook';


## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "http://creativecommons.org/licenses/by-nc/3.0/";
$wgRightsText = "Attribution-Noncommercial 3.0 Unported";
$wgRightsIcon = "http://i.creativecommons.org/l/by-nc/3.0/88x31.png";
# $wgRightsCode = "[license_code]"; # Not yet used

#Logo
//$wgLogo = 'http://www.wvodesigns.com/Logo2.png';
$wgLogo = "{$wgScriptPath}/Wiki_Logo.png";

$wgDiff3 = "/bin/diff3";

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$wgCacheEpoch = max( $wgCacheEpoch, gmdate( 'YmdHis', @filemtime( __FILE__ ) ) );

#ReCaptcha
require_once("$IP/extensions/ConfirmEdit/ReCaptcha.php"); 
$wgCaptchaClass = 'ReCaptcha';
$recaptcha_public_key = '6LdajcMSAAAAAJzUW-yxLHxDrvJUaCUZ4y0lMbPs';
$recaptcha_private_key = '6LdajcMSAAAAAOKkGrfW01R9Yq0z3NFpbdpGAuzC';


#Rights
$wgGroupPermissions['*']['createaccount'] = false;
# Disable for everyone.
$wgGroupPermissions['*']['edit']              = false;
$wgGroupPermissions['user']['edit'] = false;
$wgGroupPermissions['sysop']['edit'] = true;

// Fix the default captcha behaviour
$wgGroupPermissions['*'            ]['skipcaptcha'] = false;
$wgGroupPermissions['user'         ]['skipcaptcha'] = false;
$wgGroupPermissions['autoconfirmed']['skipcaptcha'] = false;
$wgGroupPermissions['bot'          ]['skipcaptcha'] = false; // registered bots
$wgGroupPermissions['sysop'        ]['skipcaptcha'] = true;
 
$wgCaptchaTriggers['edit']          = true;
$wgCaptchaTriggers['create']        = true;
$wgCaptchaTriggers['createaccount'] = true;

#WikiEditor
require_once( "$IP/extensions/WikiEditor/WikiEditor.php" );
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;
$wgDefaultUserOptions['wikieditor-preview'] = 1;



# Short URL Rewrite
$wgScriptPath	    = "/wiki";
$wgScript           = "$wgScriptPath/index.php";
$wgRedirectScript   = "$wgScriptPath/redirect.php";
 
$wgArticlePath      = "$wgScriptPath/$1";

# Flash Stuff
#$wgFileExtensions[] = 'swf';
#require_once("$IP/extensions/Flash/Flash.php");


//Google Analytics
//require_once( "$IP/extensions/googleAnalytics/googleAnalytics.php" );
 
# Replace xxxxxxx-x with YOUR GoogleAnalytics UA number
//$wgGoogleAnalyticsAccount = "UA-4306196-1";
 
# Optional Variables (both default to true)
//$wgGoogleAnalyticsIgnoreSysops = true;
//$wgGoogleAnalyticsIgnoreBots = true;

# EmbedVideo Extension
//require_once("$IP/extensions/EmbedVideo/EmbedVideo.php");

# Nuke
//require_once("$IP/extensions/Nuke/Nuke.php");

// Bread Crumbs
//$wgUseCategoryBrowser = true;
//require_once("extensions/CategoryBreadCrumbs.php");

# Delete Batch
//require_once("$IP/extensions/DeleteBatch/DeleteBatch.php");

#  Phalanx
# require_once("$IP/extensions/Phalanx/Phalanx.php");

//require_once( "$IP/extensions/Cite/Cite.php" );
//$wgCiteEnablePopups = true;

$wgUpgradeKey = '783b6fab7ea1614c';

